language: swift
os: osx
osx_image: xcode10.2

install:
  - gem update cocoapods

before_script:
  - pod lib lint --skip-tests --verbose

xcode_destination: platform=macOS
xcode_project: SwiftLSPClient.xcodeproj
xcode_scheme: SwiftLSPClient 
