language: swift
os: osx
osx_image: xcode10.1
cache:
  directories:
    - Carthage

install:
  - gem update cocoapods --pre
  - carthage bootstrap --verbose --platform macOS --cache-builds --no-use-binaries

before_script:
  - pod lib lint --skip-tests --verbose

xcode_destination: platform=macOS
xcode_project: SwiftLSPClient.xcodeproj
xcode_scheme: SwiftLSPClient 
