name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: xcodebuild test
        run: set -o pipefail && xcodebuild test -scheme SwiftLSPClient -destination "platform=macOS" | xcpretty
