name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Test on destination ${{ matrix.destination }}
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ["platform=macOS"]
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: carthage bootstrap --use-xcframeworks
    - name: xcodebuild ${{ matrix.destination }}
      run: set -o pipefail && xcodebuild test -scheme SwiftLSPClient -destination "${{ matrix.destination }}" | xcpretty
    - name: SPM ${{ matrix.destination }}
      run: swift test
