name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: xcodebuild test
        run: xcodebuild test -scheme SwiftLSPClient -destination "platform=macOS"
